const upload = require('./upload/upload.service.js');
const recording = require('./recording/recording.service.js');
const transcriptParser = require('./transcript-parser/transcript-parser.service.js');
const speaker = require('./speaker/speaker.service.js');
const transcript = require('./transcript/transcript.service.js');
const meetingRecord = require('./meeting-record/meeting-record.service.js');
const users = require('./users/users.service.js');
const mailHistory = require('./mail-history/mail-history.service.js');
const team = require('./team/team.service.js');
const teamUser = require('./team-user/team-user.service.js');
const calendarEvent = require('./calendar-event/calendar-event.service.js');
const transcriptKeyword = require('./transcript-keyword/transcript-keyword.service.js');
const transcriptKeywordRecapConfig = require('./transcript-keyword-recap-config/transcript-keyword-recap-config.service.js');
const transcriptCoaching = require('./transcript-coaching/transcript-coaching.service.js');
const cronjobCalendarEvent = require('./cronjob-calendar-event/cronjob-calendar-event.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(upload);
  app.configure(recording);
  app.configure(transcriptParser);
  app.configure(speaker);
  app.configure(transcript);
  app.configure(meetingRecord);
  app.configure(users);
  app.configure(mailHistory);
  app.configure(team);
  app.configure(teamUser);
  app.configure(calendarEvent);
  app.configure(cronjobCalendarEvent);
  app.configure(transcriptKeyword);
  app.configure(transcriptKeywordRecapConfig);
  app.configure(transcriptCoaching);
};
