const upload = require('./upload/upload.service.js');
const recording = require('./recording/recording.service.js');
const transcriptParser = require('./transcript-parser/transcript-parser.service.js');
const speaker = require('./speaker/speaker.service.js');
const transcript = require('./transcript/transcript.service.js');
const meetingRecord = require('./meeting-record/meeting-record.service.js');
const users = require('./users/users.service.js');
const mailHistory = require('./mail-history/mail-history.service.js');
const team = require('./team/team.service.js');
const teamUser = require('./team-user/team-user.service.js');
const calendarEvent = require('./calendar-event/calendar-event.service.js');
const transcriptKeyword = require('./transcript-keyword/transcript-keyword.service.js');
const transcriptKeywordRecapConfig = require('./transcript-keyword-recap-config/transcript-keyword-recap-config.service.js');
const transcriptCoaching = require('./transcript-coaching/transcript-coaching.service.js');
const cronjobCalendarEvent = require('./cronjob-calendar-event/cronjob-calendar-event.service.js');
const teamCompetitor = require('./team-competitor/team-competitor.service.js');
const transcriptExport = require('./transcript-export/transcript-export.service.js');
const teamSynonym = require('./team-synonym/team-synonym.service.js');
const speakersData = require('./speakers-data/speakers-data.service.js');
const analyticsTalkToListen = require('./analytics-talk-to-listen/analytics-talk-to-listen.service');
const analyticsTalkToListenExport = require('./analytics-talk-to-listen/analytics-talk-to-listen-export.service');
const question = require('./question/question.service.js');
const answer = require('./answer/answer.service.js');

// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(upload);
  app.configure(recording);
  app.configure(transcriptParser);
  app.configure(speaker);
  app.configure(transcript);
  app.configure(meetingRecord);
  app.configure(users);
  app.configure(mailHistory);
  app.configure(team);
  app.configure(teamUser);
  app.configure(calendarEvent);
  app.configure(cronjobCalendarEvent);
  app.configure(transcriptKeyword);
  app.configure(transcriptKeywordRecapConfig);
  app.configure(transcriptCoaching);
  app.configure(teamCompetitor);
  app.configure(transcriptExport);
  app.configure(teamSynonym);
  app.configure(speakersData);
  app.configure(analyticsTalkToListen);
  app.configure(analyticsTalkToListenExport);
  app.configure(question);
  app.configure(answer);
};
